import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistRegular = localFont({
  src: "../public/assets/fonts/GeistRegular.ttf",
  variable: "--font-geist-regular",
});

const geistBold = localFont({
  src: "../public/assets/fonts/GeistBold.ttf",
  variable: "--font-geist-bold",
});

const geistSemiBold = localFont({
  src: "../public/assets/fonts/GeistSemiBold.ttf",
  variable: "--font-geist-semibold",
});

const geistMedium = localFont({
  src: "../public/assets/fonts/GeistMedium.ttf",
  variable: "--font-geist-medium",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { DynamicPagesList } from "@/components/dynamic-content-page/DynamicPagesList";
import SmoothScroll from "@/components/ui/SmoothScroll";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${geistRegular.variable} ${geistBold.variable} ${geistSemiBold.variable} ${geistMedium.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll />
        {children}
        <Footer />
        <DynamicPagesList />
      </body>
    </html>
  );
}
